<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sms.Shared.Kernel\Sms.Shared.Kernel.csproj" />
    <ProjectReference Include="..\Sms.Modules.Attendance\Sms.Modules.Attendance.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
